# greetings_lastweek.py

greeting_word = [
    "โค้งสุดท้ายแล้ว! มาช่วยกันเติมคำสแลงให้ปัง 💥<br> Final lap! Let’s make this slang list shine!",
    "เหลืออีกไม่กี่วันแล้วนะ มาใส่คำสแลงกันเร็ว 🚀<br> Just days left—add your slang now!",
    "อาทิตย์สุดท้ายแล้ว ใครไม่มาเติมคือพลาด 😎<br> Last week—don’t miss your chance!",
    "นี่คือโอกาสสุดท้ายที่คำของคุณจะอยู่ในตำนาน 📜<br> Your last chance to make slang history!",
    "อีกนิดเดียวพจนานุกรมก็จะเสร็จแล้ว มาช่วยปิดจ๊อบกัน! 🏁<br> Almost done—help us cross the finish line!",
    "มาช่วยกันปิดท้ายให้สวยงาม ✨<br> Let’s give it a grand finale!",
    "พจนานุกรมจะไม่สมบูรณ์ถ้าขาดคำจากคุณ 💡<br> Your words complete this dictionary!",
    "อีกแค่เสี้ยวเดียว จะพลาดเหรอ? 😏<br> We’re this close—are you gonna skip it?",
    "โค้งสุดท้ายแล้วนะ รีบปล่อยของเลย! 💣<br> Final stretch—drop your slang bomb now!",
    "เรามาถึงตอนจบแล้ว แต่ยังขาดคำเด็ดจากคุณ! 🎬<br> The finale needs your words!",
    "ไม่ช่วยตอนนี้จะช่วยตอนไหนล่ะ? ⏳<br> If not now, when?",
    "มาช่วยกันก่อนปิดสมุดพจนานุกรมเล่มนี้ 📖<br> Before we close the book, add your slang!",
    "พลังคำของคุณคือจิ๊กซอว์ชิ้นสุดท้าย 🧩<br> Your slang is the last puzzle piece!",
    "ถึงเวลาโชว์ของแล้วเพื่อน 🏆<br> Time to show off your slang skills!",
    "อย่าให้โอกาสนี้หลุดมือไปนะ 👋<br> Don’t let this chance slip away!",
    "เติมคำวันนี้ ดังกว่าตะโกนในไมค์ 🎤<br> Add slang now—it’s louder than a mic drop!",
    "นี่แหละวินาทีทองของนักสร้างคำ ✨<br> This is your golden moment!",
    "อาทิตย์หน้าจะปิดแล้วนะ รีบเลย! 🚨<br> Next week we close—act fast!",
    "ใส่คำตอนนี้ = ติดตลอดไปในตำนาน 💎<br> Add your slang now and be immortalized!",
    "ช่วยกันอีกนิดเดียว จะเสร็จแล้วจริงๆ 🙌<br> Just one last push—we’re almost done!",
    "ขาดคำคุณ เหมือนขาดวิญญาณ 😵<br> Without your slang, we’re soulless!",
    "อีกนิดเดียวจะปิดตำนานแล้ว มาร่วมเป็นส่วนหนึ่ง 📝<br> Be part of the legend before it ends!",
    "ช่วยปิดท้ายให้พจนานุกรมนี้สมบูรณ์ 🌟<br> Help us finish strong!",
    "รอบสุดท้ายแล้วนะ จัดคำเด็ดให้หน่อย 🔥<br> Last round—bring the heat!",
    "ถึงเวลาปล่อยสกิลขั้นเทพ 💫<br> Time to unleash your ultimate skill!",
    "อีกไม่กี่วันก็สายไปแล้วนะ ⏰<br> Days left before it’s too late!",
    "มาเป็นตำนานกับเราก่อนจบโปรเจกต์ 📜<br> Join the legend before the end!",
    "ช่วยเราปิดฉากอย่างยิ่งใหญ่ 🎆<br> Help us end with a bang!",
    "ทุกคำที่ใส่ตอนนี้ จะเป็นประวัติศาสตร์ 📚<br> Every word now becomes history!",
    "พลาดรอบนี้ รออีกทีก็ไม่รู้เมื่อไหร่ 📅<br> Miss this, and who knows when’s the next!",
    "อีกนิดเดียวจริงๆ เหมือนวิ่งถึงเส้นชัยแล้ว 🏃‍♂️<br> We’re almost at the finish line!",
    "ปิดตำนานแบบไม่มีคุณ… ไม่ได้หรอก! 💌<br> We can’t end without you!",
    "นี่คือรอบชิงของนักสร้างสแลง 🥇<br> This is the slang championship!",
    "เติมตอนนี้ ระบบจะจำชื่อคุณตลอดไป 🖋️<br> Add now and be remembered forever!",
    "ไม่มาเติมนี่คือใจร้ายมากนะ 😢<br> Skipping now is just cruel!",
    "พจนานุกรมรอคำจากคุณอยู่ 📢<br> The dictionary is calling your name!",
    "ใครไม่มาเติมคือพลาดโอกาสทอง 🏅<br> Don’t miss this golden chance!",
    "อีกแค่นิดเดียว จะครบ 100% แล้ว 📊<br> We’re so close to 100%!",
    "ถ้าไม่เพิ่มตอนนี้ จะเสียดายทีหลังนะ 😬<br> You’ll regret not adding now!",
    "อาทิตย์สุดท้าย ต้องจัดเต็ม! 💥<br> Final week—go all out!",
    "นี่คือวินาทีที่พจนานุกรมรอคอย ⌛<br> The moment we’ve all been waiting for!",
    "มาเติมให้ครบ ก่อนปิดตำนาน 🔒<br> Add before the gates close!",
    "จังหวะนี้ต้องรีบพิมพ์แล้วล่ะ ⌨️<br> Now’s the time to type it in!",
    "ใส่คำคุณตอนนี้ คือของขวัญชิ้นสุดท้าย 🎁<br> Your word is the final gift!",
    "ปิดงานทั้งที ต้องมีชื่อคุณอยู่ในนี้ 📜<br> End it with your name in the record!",
    "นี่คือโอกาสสุดท้ายจริงๆ แล้วนะ 🛑<br> This really is the last chance!",
    "อีกนิดเดียวจะเสร็จแล้ว อย่าหายไปนะ 💬<br> We’re almost done—don’t disappear now!",
    "เวลานับถอยหลังแล้ว! ⏳<br> The countdown has begun!",
    "ใส่คำตอนนี้ = ได้เกียรติบัตรในใจเรา 💖<br> Add now and earn our eternal respect!",
    "อย่าปล่อยให้ที่ว่างนี้เหงาเลย 🪑<br> Don’t leave this space lonely!",
    "นี่คือภารกิจสุดท้ายของคุณ! 🛠️<br> This is your final mission!",
    "ถ้าไม่ช่วยตอนนี้ จะเสียใจไปอีกนาน 😱<br> You’ll regret missing this!",
    "อีกไม่กี่วันจะปิดแล้วจริงๆ นะ 🤯<br> Just days until it’s really over!",
    "เติมคำสแลงก่อนหมดเวลา! 🕒<br> Add slang before time runs out!",
    "ถ้ารออีกนิด เราจะปิดรับแล้วนะ 🚪<br> Wait too long and we’ll be closed!",
    "เหลือเวลาอีกนิดเดียว จัดคำเด็ดเลย 📢<br> Last moments—give us your best slang!",
    "ใครใส่คำตอนนี้คือฮีโร่ตัวจริง 🦸‍♂️<br> Add now and be the real hero!",
    "นี่คือโอกาสสร้างชื่อให้ตัวเอง 🌟<br> Make your name legendary now!",
    "ถ้าไม่ใส่วันนี้ จะรอถึงปีหน้าเลยนะ 📆<br> Skip today and wait until next year!",
    "มาเติมความสนุกก่อนปิดเล่ม! 🎉<br> Add some fun before we close the book!",
    "นี่คือรอบสุดท้ายของการสร้างประวัติศาสตร์ 📜<br> The final round of making history!",
    "อีกนิดเดียวจะครบทุกคำแล้ว 📋<br> We’re almost full—help us get there!",
    "เหลือเวลาเท่านี้แล้วนะ ⏰<br> This is all the time we have left!",
    "ทุกคำตอนนี้คือเพชรเม็ดสุดท้าย 💎<br> Every word now is a final gem!",
    "อย่าให้โอกาสนี้หลุดมือไปอีก ❌<br> Don’t let this slip away again!",
    "นี่คือบทสรุป และคุณคือผู้เขียนตอนจบ ✍️<br> This is the ending—you write it!",
    "ใส่คำตอนนี้ คือฝากชื่อไว้ตลอดไป 🖋️<br> Add your word now to be remembered!",
    "พจนานุกรมจะปิดแล้ว ใครยังไม่เติม รีบ! 🚨<br> Dictionary closing soon—hurry up!",
    "นี่คือครั้งสุดท้ายที่จะได้มีส่วนร่วม 💬<br> Last chance to be part of it!"
]
